# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet package

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
       versionSpec: '5.x'
       preferLatestVersion: true
       
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      id:   gitversion # id to later be referenced
     

    - name: Display GitVersion outputs (step output)
      run: |
       echo "Major: ${{ steps.gitversion.outputs.major }}"
       echo "Minor: ${{ steps.gitversion.outputs.minor }}"
       echo "Patch: ${{ steps.gitversion.outputs.patch }}"
     
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
    
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}
    
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore TestApp/TestApp.sln
      - name: Build
        run: dotnet build TestApp/TestApp.sln --configuration Release --no-restore
      
